### ISSUE TITLE
Will legacy data be moved over here as well?

### ISSUE THREAD

**Issue by Awedtan** [Kengxxiao/ArknightsGameData_YoStar#1]
This repository is missing some legacy data such as level files for past limited-time events or events that haven't had a rerun yet. These files are still accessible in the old repository. Will this data also be moved here? Or is this repository a fresh start?

If it helps, here are the events I've noticed are missing:
act13mini
act12mini
act19side
act20side
act1bossrush
act11mini
act18side
act10mini
act9mini
act17d7
act8mini
act1lock
act7mini
act17d0
act15d5
act13d0
act10d5
act7d5
act6d5
act4d0

Thanks for all your hard work 👍

**Comment by Kengxxiao** [comment]
No, It's a fresh start on yostar servers.  
The main reason is to avoid conflicts with old data (different formats), and secondly, all event levels can be found in cn part of main repository.

**Comment by Awedtan** [comment]
Got it, thanks for the info.
