### ISSUE TITLE
Bad JSON in ko_KR/gamedata/excel/building_data.json

### ISSUE THREAD

**Issue by orzFly** [Kengxxiao/ArknightsGameData_YoStar#4]
https://github.com/Kengxxiao/ArknightsGameData_YoStar/blob/a2d7ab70446569af9f9f7e54588c17f48cc52af0/ko_KR/gamedata/excel/building_data.json

`jq: parse error: Object keys must be strings at line 93684, column 11`

![image](https://github.com/Kengxxiao/ArknightsGameData_YoStar/assets/158528/527551c5-49d7-4f59-ba0b-4dc2507ee642)

<details>
<summary>Script used to find the problem</summary>

```shellSession
$ find -name "*.json" | while read i; do cat "$i" | jq 0 >/dev/null || echo $i; done
jq: parse error: Object keys must be strings at line 93684, column 11
./ko_KR/gamedata/excel/building_data.json
```
</details>

**Comment by Kengxxiao** [comment]
Fixed

**Comment by orzFly** [comment]
Thank you, as always!
